name: 'Push course'
description: 'Push to a course repository'
inputs:
  message:
    description: 'Message to use for the commit'
    required: false
    default: 'Update'
  repo:
    description: 'Destination repository'
    required: true
  token:
    description: 'Github token'
    required: true
  user:
    description: 'User of the repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
    - ${{ inputs.repo }}
    - ${{ inputs.token }}
    - ${{ inputs.user }}
