name: 'Push course'
description: 'Push to a course repository'
author: 'Quentin Fortier <qpfortier@gmail.com>'
branding:
  icon: 'link'
  color: 'green'
inputs:
  repo:
    description: 'Destination repository'
    required: true
  
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        REPO=${{ inputs.repo }}
        CLONE_DIR=$(mktemp -d)
        git config --global user.email "qpfortier@gmail.com"
        git config --global user.name "Quentin Fortier"
        git clone "https://fortierq:${{ inputs.GITHUB_TOKEN }}@github.com/$REPO.git" "$CLONE_DIR"
        rm -rf "$CLONE_DIR/files"
        img() {
            img=$(dirname "$file")/img
            if [ -d $img ]; then
              cp -r $img "$CLONE_DIR/"$(dirname "$file")
            fi
        }
        ipynb() {
          mkdir -p "$CLONE_DIR/"$(dirname "$file")
          img
          if [[ $file == *.ipynb ]]; then
            jupyter nbconvert "$file" --to ipynb --output "$CLONE_DIR/$file" --allow-errors \
            --TagRemovePreprocessor.enabled=True \
            --TagRemovePreprocessor.remove_input_tags hide \
            --TagRemovePreprocessor.remove_cell_tags cor
          else
            cp $file "$CLONE_DIR/"$(dirname "$file")
          fi
        }
        ipynb_cor() {
          img
          cor=${file%.*}_cor.${file#*.}
          rm -f "$CLONE_DIR/$file"
          jupyter nbconvert "$file" --to ipynb --output "$CLONE_DIR/$file" --allow-errors \
          --TagRemovePreprocessor.enabled=True \
          --TagRemovePreprocessor.remove_input_tags hide
        }

        while read file; do
          echo "Processing $file"
          if [ ! -f "$CLONE_DIR/$file" ]; then
            ipynb
          fi
        done < student.txt

        while read file; do
          cor=${file%.*}_cor.${file#*.}
          if [ ! -f "$CLONE_DIR/$file" ]; then
            ipynb_cor
          fi
        done < cor.txt

        cd "$CLONE_DIR"
        git add .
        git commit -m "${{ github.event.head_commit.message }}"
        git push "https://fortierq:${{ inputs.GITHUB_TOKEN }}@github.com/$REPO.git" --set-upstream main
